export const TYPE_OPTIONS = [
  { value: "stone", label: "Stone" },
  { value: "stone-motherlode", label: "Stone Motherlode" },
  { value: "ore", label: "Ore" },
  { value: "ore-motherlode", label: "Ore Motherlode" },
  { value: "wood", label: "Wood" },
  { value: "animal", label: "Animal" },
  { value: "animal-boss", label: "Animal Boss" },
  { value: "mob", label: "Mob" },
  { value: "mob-boss", label: "Mob Boss" },
  { value: "well", label: "Well" },
  { value: "grave", label: "Grave" },
  { value: "tactical-house", label: "Tactical House" },
  { value: "tactical-fire", label: "Tactical Fire" },
  { value: "tactical-fish", label: "Tactical Fish" },
];

export const RESOURCE_OPTIONS = [
  { value: "yew", type: "wood" },
  { value: "birch", type: "wood" },
  { value: "ash", type: "wood" },
  { value: "oak", type: "wood" },
  { value: "spruce", type: "wood" },
  { value: "granite", type: "stone" },
  { value: "limestone", type: "stone" },
  { value: "travertine", type: "stone" },
  { value: "slate", type: "stone" },
  { value: "marble", type: "stone" },
  { value: "copper", type: "ore" },
  { value: "tin", type: "ore" },
  { value: "iron", type: "ore" },
  { value: "silver", type: "ore" },
  { value: "aurelium", type: "ore" },
  { value: "spider", type: "animal" },
  { value: "pig", type: "animal" },
  { value: "cat", type: "animal" },
  { value: "auroch", type: "animal" },
  { value: "elk", type: "animal" },
  { value: "wolf", type: "animal" },
  { value: "bear", type: "animal" },
  { value: "gryphon", type: "animal" },
  { value: "human", type: "grave" },
  { value: "elven", type: "grave" },
  { value: "monster", type: "grave" },
  { value: "stoneborn", type: "grave" },
  { value: "guinecian", type: "grave" },
  { value: "urgu", type: "mob" },
  { value: "elementals", type: "mob" },
  { value: "satyr", type: "mob" },
  { value: "aracoix", type: "mob" },
  { value: "underhill", type: "mob" },
  { value: "enbarri", type: "mob" },
  { vaule: "thralls", type: "mob" },
];
