on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: install node v12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: install eslint
      run: yarn add eslint
    - name: install babel-eslint
      run: yarn add babel-eslint
    - name: add eslint react plugin
      run: yarn add eslint-plugin-react
    - name: eslint
      uses: icrawl/action-eslint@v1
